[package]
name = "bitcoin-core-bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["codec", "compat"] }
capnp = "0.21.4"
capnp-rpc = "0.21.0"
bitcoin = "0.32.5"
anyhow = "1.0"

bitcoin-capnp-types = { git = "https://github.com/2140-dev/bitcoin-capnp-types", rev = "77a609a0058478d6c8aad24351b6baeb3e0555fc" }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "fetch_template_bench"
harness = false

